### ISSUE TITLE
老哥，你发的pojie谷歌访问助手在浏览器里打包完以后总是提示警告

### ISSUE THREAD

**Issue by 756347423** [haotian-wang/google-access-helper#1]
没法用，什么方法都试遍了，改组策略，改设置，咋整啊老哥 @haotian-wang

**Comment by haotian-wang** [comment]
新版的Chrome浏览器只允许安装来自Chrome应用商店的应用，并且如果安装的插件被Chrome发现和应用商店里的不一致，就会自动删掉。所以比较靠谱的方法，一种是用开发者模式，直接加载已解压的扩展程序，但是每次启动Chrome都会弹出警告“请停止以开发者模式运行的扩展程序”；另一种方式就是用组策略添加进白名单，比较麻烦，但是不会弹出警告。

详细安装教程可以查看：<https://github.com/haotian-wang/google-access-helper/wiki/Installation-Guide>

**Comment by 756347423** [comment]
大佬，组策略不是早就失效了吗，我自己也试过，莫非又出了新的扩展组策略？

**Comment by 756347423** [comment]
不好意思大佬，我是github新人，还没熟悉如此huge的开源社区，所以你以前发的一篇维基“installation guide”安装向导我没看到，不好意思啦

**Comment by haotian-wang** [comment]
我刚才确认了一下，打包好的crx即使断网安装也会出现“此扩展程序可能已损坏”。可能新版Chrome又进一步封杀了破解版插件，最近我再研究一下。

**Comment by 756347423** [comment]
唉，真的心累，被谷歌定义为“损坏”的破解访问助手.crx已经被我打包又删除，打包又删除，丢掉将近一百个了

**Comment by 756347423** [comment]
有没有什么应急的方法啊大神

**Comment by 756347423** [comment]
行吧，先用着，你研究结果出来了通知我下就可以；上专业平台找技术大佬果然什么都能摆平，啥玩意都能破解

**Comment by 756347423** [comment]
老哥，怎么样了

**Comment by haotian-wang** [comment]
我把[manifest.json](https://github.com/haotian-wang/google-access-helper/blob/master/manifest.json)中原来自带的key删掉，然后把扩展名改成了“谷歌访问助手破解版”，就不会显示扩展已损坏了。改完以后的扩展已经重新打包上传到[Release](https://github.com/haotian-wang/google-access-helper/releases)上了，安装时还是按照[Wiki](https://github.com/haotian-wang/google-access-helper/wiki/Installation-Guide)上写的，添加到白名单，就可以正常使用了。

**Comment by 756347423** [comment]
OK

**Comment by 756347423** [comment]
一切正常

**Comment by haotian-wang** [comment]
参考 https://www.52pojie.cn/forum.php?mod=viewthread&tid=704368&page=1

**Comment by ahsar** [comment]
Thks author

**Comment by JingDeZhe** [comment]
可以用火绒的弹窗拦截功能给拦截。。

**Comment by 1185607522** [comment]
我用开发者模式加载已解压的扩展程序,然后把我解压的扩展程序文件夹删除了,然后再重启浏览器,这时候虽然插件在Chrome上不显示了,但是Google却可以打开了,你们可以试试,不知道是什么原理

**Comment by kejianlin** [comment]
> 可以用火绒的弹窗拦截功能给拦截。。

谢谢你
