### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Herumw** [haotian-wang/google-access-helper#38]
下载火绒安全软件，然后利用这个软件的弹窗拦截功能截图屏蔽“请停用以开发者模式运行的扩展程序”就好了^_^。
plus：不过这个方法在最开始打开网页的时候还会弹出来，火绒拦截功能会马上屏蔽这个弹窗。

**Comment by prince100789** [comment]
@Herumw 你这个方法治标不治本啊, 光打开的时候弹出来就很烦了

**Comment by duanmuyan** [comment]
这个方法感觉还是很麻烦

**Comment by ddatsh** [comment]
version.dll 搞定
