### ISSUE TITLE
不知道怎么私信，题外话

### ISSUE THREAD

**Issue by 756347423** [haotian-wang/google-access-helper#5]
https://github.com/googlehosts/hosts Google hosts 怎么用？下载了个zip，解压后要干什么，直接复制 hosts？

**Comment by haotian-wang** [comment]
把`hosts-files`文件夹下面的`hosts`文件复制到`C:\Windows\System32\drivers\etc`目录下。不过现在改hosts已经没什么用了，自从十九大以后，墙又升级了，现在的hosts不到24小时就会被封掉。

**Comment by 756347423** [comment]
哦，明白
