### ISSUE TITLE
请问新版 edge 怎么设置扩展白名单？

### ISSUE THREAD

**Issue by Stars-sea** [haotian-wang/google-access-helper#56]
# 请问新版 edge 怎么设置扩展白名单？
Wiki 里面的方法我试过。两个方法都无效。。。😂

应该怎么做？

**Comment by Stars-sea** [comment]
嗯，把安装说明上的ExtensionInstallWhitelist换成[extensioninstallallowlist](https://docs.microsoft.com/DeployEdge/microsoft-edge-policies#extensioninstallallowlist)就行了😂

**Comment by a-little-headache** [comment]
其他步骤完全一样吗

**Comment by Stars-sea** [comment]
> 其他步骤完全一样吗

嗯, 只不过只有 bate 版可以直接安装 crx 正式版不行

**Comment by a-little-headache** [comment]
我是beat，注册表路径是\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\ExtensionInstallWhitelist，没用...

**Comment by a-little-headache** [comment]
我是beat，注册表路径是\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\Extensioninstallallowlist，没用...
换成\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\Extensioninstallallowlist也不行...
应该怎么弄哇

**Comment by Stars-sea** [comment]
> 我是beat，注册表路径是\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\Extensioninstallallowlist，没用...
> 换成\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\Extensioninstallallowlist也不行...
> 应该怎么弄哇


应该是这个项。。。
`计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Edge\Extensions\ExtensionInstallAllowlist`
或者
`计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Edge Bate\Extensions\ExtensionInstallAllowlist`

**Comment by a-little-headache** [comment]
刚开始设置Chrome浏览器用修改注册表的方法就不行，只能更改组策略；
现在Edge浏览器，注册表的方法依然不行。。。即使是改成你说的这个项。
Wiki里面的步骤有哪些没提及的吗？

**Comment by Stars-sea** [comment]
> 刚开始设置Chrome浏览器用修改注册表的方法就不行，只能更改组策略；

奇怪, 我的可以。我先开发者安装取得扩展 id , 然后设置白名单, 再拖动安装。

> 现在Edge浏览器，注册表的方法依然不行。。。即使是改成你说的这个项。
> Wiki里面的步骤有哪些没提及的吗？

请仔细看看我所发的那个文档, 这里有策略组的更改方法 [ExtensionInstallAllowlist](https://docs.microsoft.com/zh-cn/DeployEdge/microsoft-edge-policies#extensioninstallallowlist)

**Comment by a-little-headache** [comment]
> > 刚开始设置Chrome浏览器用修改注册表的方法就不行，只能更改组策略；
> 
> 奇怪, 我的可以。我先开发者安装取得扩展 id , 然后设置白名单, 再拖动安装。
> 
> > 现在Edge浏览器，注册表的方法依然不行。。。即使是改成你说的这个项。
> > Wiki里面的步骤有哪些没提及的吗？
> 
> 请仔细看看我所发的那个文档, 这里有策略组的更改方法 [ExtensionInstallAllowlist](https://docs.microsoft.com/zh-cn/DeployEdge/microsoft-edge-policies#extensioninstallallowlist)

刚刚添加组策略成功了，不过还是搞不懂究竟是什么导致修改注册表的方法行不通，谢谢你了哈~
