### ISSUE TITLE
失效，bs.js报错。

### ISSUE THREAD

**Issue by DuangXT** [haotian-wang/google-access-helper#59]
localStorage["popup-message"] = t["popup-message"];

昨天开始，提示bg.js报错。
重新安装依旧。。。

助手官网很早就下线了但是chrome商店还在。现在chrome商店也搜不到了。

估摸着，是凉了，撑了这么多年，没地方感谢官方，来这里感谢下吧

**Comment by yunchaolu** [comment]
刚才使用，再次连接上服务器，你可以再尝试下。

**Comment by yunchaolu** [comment]
> localStorage["popup-message"] = t["popup-message"];
> 
> 昨天开始，提示bg.js报错。
> 重新安装依旧。。。
> 
> 助手官网很早就下线了但是chrome商店还在。现在chrome商店也搜不到了。
> 
> 估摸着，是凉了，撑了这么多年，没地方感谢官方，来这里感谢下吧

> 刚才使用，再次连接上服务器，你可以再尝试下。

**Comment by maya0914** [comment]
google没问题，YouTube不行

**Comment by DuangXT** [comment]
> google没问题，YouTube不行

助手本来就说了，不支持youtube的，只有搜索、邮箱、学术、验证等等一些跟视频无关的地址可以访问

**Comment by DuangXT** [comment]
> > localStorage["popup-message"] = t["popup-message"];
> > 昨天开始，提示bg.js报错。
> > 重新安装依旧。。。
> > 助手官网很早就下线了但是chrome商店还在。现在chrome商店也搜不到了。
> > 估摸着，是凉了，撑了这么多年，没地方感谢官方，来这里感谢下吧
> 
> > 刚才使用，再次连接上服务器，你可以再尝试下。

之前确实会有问题，现在稳定了挺长一段时间了，希望只是助手的服务器偶尔抽风吧…………
