### ISSUE TITLE
what happened ?

### ISSUE THREAD

**Issue by hyyoxhk** [haotian-wang/google-access-helper#62]

**Comment by yung-chu** [comment]
猜测是喝茶

**Comment by progrui** [comment]
why delete？

**Comment by devin8358** [comment]
who has this project ? I need  help

**Comment by hyyoxhk** [comment]
> who has this project ? I need help

I had back-up this repository

https://github.com/hyyoxhk/google-access-helper.git

**Comment by haotian-wang** [comment]
并没有什么被喝茶，只是star的人太多了，怕树大招风，就删掉了。

**Comment by fakermama** [comment]
> 并没有什么被喝茶，只是star的人太多了，怕树大招风，就删掉了。

你好，这个插件怎么卸载干净啊，我用了这个之后的其他全局代理软件都不能作用谷歌浏览器了好像是这个插件没有卸载干净

**Comment by haotian-wang** [comment]
chrome://extensions，删掉就行
